# Generated by Django 3.1.7 on 2021-04-09 13:11

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NewsStories',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('pol', 'politics'), ('art', 'art news'), ('tech', 'technology news'), ('trivia', 'trivial news')], max_length=16)),
                ('region', models.CharField(choices=[('uk', 'uk news'), ('eu', 'european news'), ('w', 'word news')], max_length=16)),
                ('date', models.DateField(auto_now_add=True)),
                ('details', models.CharField(max_length=512)),
                ('author', models.ForeignKey(on_delete=builtins.callable, to='newsapp.authors')),
            ],
        ),
    ]
